name: Auto Booking
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install selenium webdriver-manager
      - run: python booking_script.py
